import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

// Zero-dependency static file server for the prebuilt Docusaurus site.
// Docusaurus builds real per-route HTML files, so no SPA fallback is
// needed -- just serve files as-is, with a 404.html fallback (also
// generated by the build) for misses. Purely read-only against ./build,
// which matters because the Deployment runs with readOnlyRootFilesystem.

const PORT = Number(process.env.PORT ?? 8080);
const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), 'build');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
};

function send404(res) {
  fs.readFile(path.join(ROOT, '404.html'), (err, data) => {
    res.writeHead(404, {'Content-Type': 'text/html; charset=utf-8'});
    res.end(err ? 'Not found' : data);
  });
}

http
  .createServer((req, res) => {
    const reqPath = decodeURIComponent(req.url.split('?')[0]);
    let filePath = path.normalize(path.join(ROOT, reqPath));
    if (!filePath.startsWith(ROOT)) {
      res.writeHead(400).end('Bad request');
      return;
    }
    if (filePath.endsWith(path.sep)) filePath = path.join(filePath, 'index.html');

    fs.stat(filePath, (statErr, stats) => {
      if (!statErr && stats.isDirectory()) filePath = path.join(filePath, 'index.html');
      fs.readFile(filePath, (readErr, data) => {
        if (readErr) return send404(res);
        const ext = path.extname(filePath);
        res.writeHead(200, {'Content-Type': MIME[ext] ?? 'application/octet-stream'});
        res.end(data);
      });
    });
  })
  .listen(PORT, () => {
    console.log(`sokrates-docs listening on ${PORT}`);
  });
