import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from docs/ folder structure -- the four Diátaxis
// categories (tutorials/how-to/reference/explanation) are top-level
// folders, each with a _category_.json controlling its sidebar label.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
